//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crusader
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hero
    {
        public int HeroId { get; set; }
        public string HeroName { get; set; }
        public int HP { get; set; }
        public int ATK { get; set; }
        public string SoulboundWeapon { get; set; }
        public string Contract { get; set; }
        public string Faction { get; set; }
        public string Class { get; set; }
    }
}
