//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crusader
{
    using System;
    using System.Collections.Generic;
    
    public partial class NPC
    {
        public int NPCId { get; set; }
        public string NPCName { get; set; }
        public string Skill { get; set; }
        public string Type { get; set; }
        public string Faction { get; set; }
    }
}
